"""Authentication module for TCA."""

from .account_storage import (
    TelegramAccountRecord,
    TelegramAccountStorage,
    TelegramAccountStorageError,
)
from .auth_session_state import (
    AUTH_SESSION_TTL_SECONDS,
    AuthSessionExpiredError,
    AuthSessionState,
    AuthSessionStateConfigError,
    AuthSessionStateError,
    AuthSessionStateNotFoundError,
    AuthSessionStateRepository,
)
from .bootstrap_token import (
    BOOTSTRAP_BEARER_TOKEN_DIGEST_KEY,
    BootstrapBearerTokenDependency,
    compute_token_sha256_digest,
    ensure_bootstrap_bearer_token,
    resolve_bootstrap_token_output_path,
)
from .encryption_utils import (
    AES_GCM_NONCE_BYTES,
    DATA_ENCRYPTION_KEY_BYTES,
    ENVELOPE_VERSION,
    EnvelopeDecryptionError,
    decrypt_with_envelope,
    encrypt_with_envelope,
    generate_data_encryption_key,
    unwrap_data_encryption_key,
    wrap_data_encryption_key,
)
from .kdf import (
    ARGON2ID_MEMORY_COST_KIB,
    ARGON2ID_PARALLELISM,
    ARGON2ID_SALT_BYTES,
    ARGON2ID_TIME_COST,
    KEY_ENCRYPTION_KEY_BYTES,
    derive_key_encryption_key,
)
from .key_material import (
    AUTH_KEY_SALT_SETTING,
    KeyMaterialError,
    resolve_key_encryption_key,
)
from .key_rotation import (
    KeyRotationAccountNotFoundError,
    KeyRotationRepository,
    KeyRotationState,
    KeyRotationStateMissingError,
)
from .service import request_login_code
from .session_storage import (
    TelegramAccountNotFoundError,
    TelegramSessionStorage,
    TelegramSessionStorageError,
)
from .unlock_modes import (
    SENSITIVE_OPERATION_LOCKED_MESSAGE,
    AuthStartupDependency,
    SensitiveOperationLockedError,
    StartupUnlockDependency,
    StartupUnlockModeError,
    UnlockState,
    get_sensitive_operation_secret,
    get_unlock_state,
    initialize_startup_unlock_mode,
    require_sensitive_operation_unlock,
    unlock_with_passphrase,
)

__all__ = [
    "AES_GCM_NONCE_BYTES",
    "ARGON2ID_MEMORY_COST_KIB",
    "ARGON2ID_PARALLELISM",
    "ARGON2ID_SALT_BYTES",
    "ARGON2ID_TIME_COST",
    "AUTH_KEY_SALT_SETTING",
    "AUTH_SESSION_TTL_SECONDS",
    "BOOTSTRAP_BEARER_TOKEN_DIGEST_KEY",
    "DATA_ENCRYPTION_KEY_BYTES",
    "ENVELOPE_VERSION",
    "KEY_ENCRYPTION_KEY_BYTES",
    "SENSITIVE_OPERATION_LOCKED_MESSAGE",
    "AuthSessionExpiredError",
    "AuthSessionState",
    "AuthSessionStateConfigError",
    "AuthSessionStateError",
    "AuthSessionStateNotFoundError",
    "AuthSessionStateRepository",
    "AuthStartupDependency",
    "BootstrapBearerTokenDependency",
    "EnvelopeDecryptionError",
    "KeyMaterialError",
    "KeyRotationAccountNotFoundError",
    "KeyRotationRepository",
    "KeyRotationState",
    "KeyRotationStateMissingError",
    "SensitiveOperationLockedError",
    "StartupUnlockDependency",
    "StartupUnlockModeError",
    "TelegramAccountNotFoundError",
    "TelegramAccountRecord",
    "TelegramAccountStorage",
    "TelegramAccountStorageError",
    "TelegramSessionStorage",
    "TelegramSessionStorageError",
    "UnlockState",
    "compute_token_sha256_digest",
    "decrypt_with_envelope",
    "derive_key_encryption_key",
    "encrypt_with_envelope",
    "ensure_bootstrap_bearer_token",
    "generate_data_encryption_key",
    "get_sensitive_operation_secret",
    "get_unlock_state",
    "initialize_startup_unlock_mode",
    "request_login_code",
    "require_sensitive_operation_unlock",
    "resolve_bootstrap_token_output_path",
    "resolve_key_encryption_key",
    "unlock_with_passphrase",
    "unwrap_data_encryption_key",
    "wrap_data_encryption_key",
]
